# Koishi 配置文件示例

plugins:
  mai-queue:
    defaultMachineCount: 5
    defaultPlayTimePerPerson: 15
    playersPerMachine: 2
    nearcadeApiToken: ""
    nearcadeBaseUrl: "https://nearcade.cn"
    debug: false
    arcades:
      wujiaochang:
        config:
          name: 上海五角场百联 ZX 造趣场 AKIBAGO
          aliases: [wjc, 五角场]
          machineCount: 5
          notice: 冬暖夏暖，记得备短袖
          groupWhitelist: ["123456789"]
          enableNearcade: false
          nearcadeId: 0

      youfang:
        config:
          name: 悠方星河奇迹体验馆
          aliases: [yf, 悠方]
          machineCount: 4
          notice: 欢迎来到悠方店！
          groupWhitelist: []
          enableNearcade: true
          nearcadeId: 16342

      liehuo:
        config:
          name: 街机烈火
          aliases: [lh, 烈火]
          machineCount: 8
          address: 上海市静安区江宁路77号恒顺大楼4层
          directionGuide: |
            南京西路地铁站1号口步行430米
          notice: 欢迎来到烈火！
          groupWhitelist: []
          enableNearcade: true
          nearcadeId: 10001
